name: gallery_picker
description: Gallery Picker is a flutter package that will allow you to pick media file(s), manage and navigate inside your gallery with modern tools and views.
version: 0.5.1
homepage: https://github.com/FlutterWay/gallery_picker

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  photo_gallery: ^2.2.1
  permission_handler: ^11.4.0
  transparent_image: ^2.0.1
  video_player: ^2.9.2
  device_info_plus: ^11.3.0
  get: ^4.7.2
  video_thumbnail: ^0.5.3
  intl: ^0.19.0
  page_transition: ^2.2.1
  bottom_sheet_scaffold: ^0.1.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  photo_gallery:
    git:
      url: https://github.com/DeuMiAn/photo_gallery.git
      ref: master
  
